import Head from "next/head";
import {useState, useEffect} from "react";

import styles from "../styles/Home.module.css";

import {getList} from "./api/sheets";

export default function App({finalData}) {
  const [data, setData] = useState([]);

  useEffect(() => setData(finalData), [finalData]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      {/* map de la data, devolviendo cards con cada producto */}
      <main className={styles.main}>
        <h1 className={styles.title}>Fetch de productos!</h1>
        <div className={styles.grid}>
          {data.map((card) => (
            <a key={card.id} className={styles.card} href="">
              <h2>{card.product} &rarr;</h2>
              <p>{card.description}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
}
//función getStaticProps para obtener la información a través de la función GetList y la genera de forma estática, que es la encargada de fetchear la data. Una vez obtenidos los datos, se tienen que parsear en JSON para poder manipularlos
export async function getStaticProps() {
  const data = await getList();
  const dataStringified = JSON.stringify(data);
  const dataParsed = await JSON.parse(dataStringified);

  //Se retorna un objeto props, que puede ser utilizado por la función App como parámetro.
  return {
    props: {
      finalData: dataParsed.slice(1, dataParsed.length),
    },
    revalidate: 10, //seconds
  };
}
